[FIX] util/fields : rename relation field
odoo/upgrade-util pull request #12
Opened 2023-11-23 09:42 UTC by thni-odoo

This commit aims to rename custom relation field which are being renamed during upgrade.

Issue:
X is standard M2O field 
Y is a custom O2M field to X
When the X is renamed to Z during upgrade,
Y field will still have old name X in relation_field which will then result in field issue 
which I am facing while enabling a studio view.

2023-11-23 09:42 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/upgrade-util/pull/12).

2023-11-23 14:27 UTC, KangOl requested changes
The query is somewhat misplaced.
Can you move it to line 412 and add a short comment explaining what it is about?

2023-11-23 14:27 UTC, KangOl commented on src/util/fields.py
> +           AND relation_field=%s
Just formatting
```suggestion
           SET relation_field = %s
         WHERE relation = %s
           AND relation_field = %s
```

2023-11-24 06:30 UTC, thni-odoo commented on src/util/fields.py
> +           AND relation_field=%s
Sure!

2023-12-11 09:48 UTC, thni-odoo commented on src/util/fields.py
> +           AND relation_field=%s
@KangOl Gentle Reminder!

2024-01-02 13:34 UTC, thni-odoo commented
@KangOl Gentle Reminder!

2024-01-02 13:52 UTC, KangOl commented
> [!WARNING]  
> Some CI checks were not successful.

Can you please rebase all your branches to ensure they are up-to-date?

2024-01-04 09:54 UTC, thni-odoo commented
@KangOl all branches are re-based but still upgradeci doesn't seems happy with it.

2024-01-04 10:31 UTC, KangOl commented on src/util/fields.py
> +        )
Can actually be dedent.
```suggestion

    # Updates custom field relation name to match the renamed standard field during upgrade.
    cr.execute(
        """
            UPDATE ir_model_fields
               SET relation_field = %s
             WHERE relation = %s
               AND relation_field = %s
               AND state = 'manual'
        """,
        [new, model, old],
    )
```

2024-01-04 10:42 UTC, thni-odoo commented
Changes Done!

2024-01-04 12:17 UTC, KangOl commented
upgradeci retry with always only base

2024-01-08 12:04 UTC, thni-odoo commented
@KangOl matt looks happy now. So, a gentle reminder ;)

2024-01-08 13:25 UTC, KangOl commented
@robodoo r+

2024-01-08 16:07 UTC, closed without merging