[IMP] util/fields: update default when converting to html
odoo/upgrade-util pull request #156
Opened 2024-10-24 16:33 UTC by diagnoza

One could use Python escape sequences in text fields. When converting a field to HTML, they will no longer work, so replace them with HTML tags.

Before:
```
+--------------------------------------------------------------------------------------------------------------------------------------+
| json_value                                                                                                                           |
|--------------------------------------------------------------------------------------------------------------------------------------|
| "Mise en place du chantier\n\nIntervention pour une mise en arrêt de la chaudière\n\nVérification responsable\nRepli fin de travaux" |
+--------------------------------------------------------------------------------------------------------------------------------------+
```
After:
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| json_value                                                                                                                                          |
|-----------------------------------------------------------------------------------------------------------------------------------------------------|
| "Mise en place du chantier<br/><br/>Intervention pour une mise en arrêt de la chaudière<br/><br/>Vérification responsable<br/>Repli fin de travaux" |
+-----------------------------------------------------------------------------------------------------------------------------------------------------+
```

[opw-4133947](https://www.odoo.com/odoo/project/6443/tasks/4133947)

2024-10-24 16:33 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/upgrade-util/pull/156.png)](https://mergebot.odoo.com/odoo/upgrade-util/pull/156)

2024-10-25 12:52 UTC, KangOl requested changes

2024-10-25 12:52 UTC, KangOl commented on src/util/fields.py
> +                                )
Use `pg_text2html`

2024-10-25 12:52 UTC, KangOl commented on src/util/fields.py
> +                                    '\t', '&nbsp;&nbsp;&nbsp;&nbsp;'
This should be part of `pg_text2html`.
Instead of 4 spaces, we can use the `&emsp;` entity (em space, [U+2003](https://unicode-explorer.com/c/2003))

2024-10-28 12:16 UTC, KangOl commented on src/util/fields.py
> +                                    '\t', '&nbsp;&nbsp;&nbsp;&nbsp;'
> we can use the `&emsp;` entity

Or just `&Tab;`.

2024-10-30 20:49 UTC, diagnoza commented
CI seems wrong to indicate a syntax error.

2024-10-31 08:01 UTC, aj-fuentes commented
You cannot use f-strings in the utils. It must be Python2 compatible.

2024-11-12 15:48 UTC, diagnoza commented
upgradeci retry

2025-01-22 09:53 UTC, diagnoza commented
@aj-fuentes would you have another look?

2025-01-22 10:13 UTC, KangOl commented on src/util/fields.py
> +            """.format(json_value_html),
Use `format_query`

2025-01-22 14:29 UTC, KangOl commented
upgradeci retry with always only account approvals base calendar crm event fleet gamification helpdesk hr hr_appraisal hr_contract hr_holidays hr_payroll hr_recruitment hr_referral l10n_be_hr_contract_salary l10n_multilang lunch maintenance mrp mrp_plm product purchase purchase_requisition repair sale sale_management sale_subscription sale_temporal stock website_sale_stock website_slides website_twitter_wall

2025-01-22 14:33 UTC, KangOl commented on src/util/fields.py
> +        format_query(cr, query, sql.Literal(json_value_html), sql.Literal(field), sql.Literal(model))
You still need to execute the query. And the json_value_html is not a Literal.
```suggestion
        query = """
                UPDATE ir_default AS d
                   SET json_value = {}
                  FROM ir_model_fields AS imf
                 WHERE imf.name = %s
                   AND imf.model = %s
                   AND imf.id = d.field_id
                """
        cr.execute(format_query(cr, query, sql.SQL(json_value_html)), [field, model])
```

2025-01-22 15:56 UTC, KangOl approved these changes
@robodoo r+

![](https://cdn2.thecatapi.com/images/-R_ccKPYo.jpg)

2025-01-23 12:02 UTC, closed without merging