[REM] core: remove current_thread().testing
odoo/upgrade-util pull request #164
Opened 2024-11-12 07:50 UTC by kmagusiak

odoo/odoo#186884
task-4270485

2024-11-12 07:50 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/upgrade-util/pull/164.png)](https://mergebot.odoo.com/odoo/upgrade-util/pull/164)

2024-11-12 10:03 UTC, KangOl commented
upgradeci retry with always only base

2024-11-12 10:11 UTC, KangOl requested changes

2024-11-12 10:11 UTC, KangOl commented on src/base/tests/test_util.py
> +    testing = getattr(thread, "testing", False)
Always `False` with new implementation.
```suggestion
    testing = getattr(modules.module, "current_test", False) or getattr(thread, "testing", False)
```

2025-02-26 10:43 UTC, ryv-odoo commented
Can you check  it @KangOl ? Thx

2025-02-26 10:52 UTC, KangOl approved these changes
@robodoo r+

![](https://cdn2.thecatapi.com/images/cuc.jpg)

2025-02-26 11:00 UTC, robodoo commented
@kmagusiak @KangOl linked pull request(s) odoo/enterprise#73634, odoo/odoo#186884 not ready. Linked PRs are not staged until all of them are ready.

2025-02-26 19:30 UTC, closed without merging