[FIX] core: odoo.orm.domains
odoo/upgrade-util pull request #178
Opened 2024-12-23 13:50 UTC by kmagusiak

Use the implementation of `Domain` to normalize domains. Note that this also distributes NOT conditions.

*Dependency*: https://github.com/odoo/odoo/pull/171291

2024-12-23 13:50 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/upgrade-util/pull/178.png)](https://mergebot.odoo.com/odoo/upgrade-util/pull/178)

2025-01-17 17:05 UTC, KangOl commented
upgradeci retry with always only account_inter_company_rules hr_holidays stock

2025-01-17 17:23 UTC, KangOl commented on src/base/tests/test_util.py
Those changes breaks the tests in older versions.

2025-01-20 17:28 UTC, KangOl commented on src/base/tests/test_util.py
> +
Most of the diff is about the `"!", "!"` that are removed. We can handle these with unpacking.
```suggestion
USE_ORM_DOMAIN = util.misc.version_gte("saas~18.2")
NOTNOT = () if USE_ORM_DOMAIN else ("!", "!")
```

2025-01-20 17:28 UTC, KangOl commented on src/base/tests/test_util.py
> +            match_domain = ["!", "!", ("partner_id.friend_id", "=", 2)]
```suggestion
        match_domain = [*NOTNOT, ("partner_id.friend_id", "=", 2)]
```

Same for all other changes.

2025-01-20 23:01 UTC, KangOl requested changes

2025-01-21 10:21 UTC, KangOl approved these changes
@robodoo r+

![](https://cdn2.thecatapi.com/images/7ho.jpg)

2025-01-21 10:21 UTC, KangOl commented on src/base/tests/test_util.py
> +        expected = ["!", (old_name, "!=", True)] if USE_ORM_DOMAIN else ["!", "!", (old_name, "=", True)]
Note that it show that the domain simplification could still be improved.

2025-01-21 10:21 UTC, KangOl commented on src/base/tests/test_util.py
> +            ),
Same for those case.

2025-01-21 10:59 UTC, kmagusiak commented on src/base/tests/test_util.py
> +        expected = ["!", (old_name, "!=", True)] if USE_ORM_DOMAIN else ["!", "!", (old_name, "=", True)]
Actually, using the Domain results in `[(old_name, '=', True)]`, but the inverse boolean just does `[..., *(~Domain(some_leaf)), ...]` and does not normalize the whole domain.

2025-01-21 17:40 UTC, closed without merging

2025-01-22 08:07 UTC, aj-fuentes commented on src/util/domains.py
> +    if not version_gte("saas~18.2"):
Shouldn't we make this 18.1 as the [original](https://github.com/odoo/upgrade-util/pull/99) patch (and the odoo/odoo part) was merged there?

2025-01-22 10:21 UTC, kmagusiak commented on src/util/domains.py
> +    if not version_gte("saas~18.2"):
I waited especially for changes in domains for **18.2**.
The main one is having semantically equivalent complements of domains. For example: `['!', ('opt_date', '>', '2020-01-01')]` is not equivalent to `[('opt_date', '<=', '2020-01-01')]` because of null value handling - so when building/translating domains this is now taken into account and the rewrite does not happen. Before 18.2, `distribute_not` has this "bug" and it is part of domain building.

2025-01-22 10:45 UTC, aj-fuentes commented on src/util/domains.py
> +    if not version_gte("saas~18.2"):
Don't we need to keep then both? Or we don't care about upgrading to 18.1 with the pre-18.1 way?

2025-01-22 15:27 UTC, kmagusiak commented on src/util/domains.py
> +    if not version_gte("saas~18.2"):
In 18.1, you are migrated using the old `normalize_domain` function. As of 18.2, you are migrated using the Domain object which distributes the not values. In 18.2, we fix the distribution of *not* for some edge cases, so upgrading using either method is correct.