[FIX] util/fields : update depends on rename
odoo/upgrade-util pull request #21
Opened 2023-12-11 06:57 UTC by thni-odoo

Currently we are not updating the dependencies for custom compute fields which leads to test crawler failure when it tries to access the view and give: KeyError: 'old_field_name'

Full error 
```bash
2023-12-11 06:32:37,756 926 ERROR thni_14.0 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('account.menu_action_move_out_invoice_type', 126, 'Accounting > Customers > Invoices', 206) to the failing menus 
Traceback (most recent call last):
  File "/tmp/tmpmzpbd93k/migrations/base/tests/test_mock_crawl.py", line 238, in crawl_menu
    self.mock_action(action_vals)
  File "/tmp/tmpmzpbd93k/migrations/base/tests/test_mock_crawl.py", line 394, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
  File "/tmp/tmpmzpbd93k/migrations/base/tests/test_mock_crawl.py", line 423, in mock_view_form
    [data] = record.read(fields_list)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3024, in read
    f = self._fields[dotname.split('.')[0]]
KeyError: 'invoice_payment_state'

2023-12-11 06:58 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/upgrade-util/pull/21).

2023-12-11 14:06 UTC, KangOl commented
Don't inject variables into the SQL via `.format()`.
And you can't blindly replace the value into the `depends` column. It's a comma separated list of dotted path to fields.

2023-12-11 14:07 UTC, KangOl commented
upgradeci retry with always only crm

2023-12-12 10:45 UTC, thni-odoo commented
@KangOl  Changes Done!

2023-12-12 17:26 UTC, KangOl commented
No. As said, you can't just blindly replace the matching part without verifying it apply on the correct model.

Actually, it should be part of the `_update_field_usage_multi` function, like done with `adapt_related`. I don't think a dedicated method is needed, but you should use the same technique as `adapt_related` and use `_adapt_one_domain` to correctly rename the field names.

2024-01-01 04:34 UTC, thni-odoo commented
upgradeci retry

2024-01-02 08:48 UTC, thni-odoo commented
@KangOl Changes are done as suggested currently i have made a method can you please suggest me where to embed the code.

2024-01-18 13:10 UTC, thni-odoo commented
@KangOl Gentle Reminder !

2024-01-18 14:03 UTC, KangOl requested changes

2024-01-18 14:03 UTC, KangOl commented on src/util/fields.py
> +def adapt_depends(cr, model, old, new):
- missing loop on inherits
 - verify the model

```suggestion
def adapt_depends(cr, model, old, new, skip_inherit=()):
    _validate_model(model)
```

2024-01-18 14:03 UTC, KangOl commented on src/util/fields.py
> +            temp_depends[i] = domain[0][0] if domain else temp_depends[i]
Useless write itself.
```suggestion
            if domain:
                temp_depends[i] = domain[0][0]
```

2024-01-19 13:20 UTC, thni-odoo commented
@KangOl Suggested Changes Done!

2024-01-29 12:10 UTC, thni-odoo commented
@KangOl Gentle Reminder!

2024-02-09 09:37 UTC, thni-odoo commented
@KangOl Gentle Reminder!

2024-02-12 16:00 UTC, KangOl commented
@robodoo r+

2024-02-12 23:11 UTC, closed without merging