[IMP] base version: lower from warning to info
odoo/upgrade-util pull request #95
Opened 2024-06-11 06:28 UTC by clbr-odoo

In Odoofin, we don't have a master branch, we always update current stable version (17.0 at the moment) through module migration scripts. This was previously handled by internal at each major version update. We now handle the scripts in the accounting team, thus have an upgrade CI.

The warning modified in this PR seems to be legitimally raised, since base is not changed, it is probably skipped in the update even if we do the upgrade with `-u all`. The warning level is preventing us to merge without admin rights, thus we propose to lower the warning to info level.

Example of build with this warning: https://runbot.odoo.com/runbot/build/63601210

2024-06-11 06:28 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/upgrade-util/pull/95.png)](https://mergebot.odoo.com/odoo/upgrade-util/pull/95)

2024-06-11 06:33 UTC, clbr-odoo commented
@KangOl Hello :wave: 
I already discussed this problem a bit with Alvaro, one of his possible solution was to manually set the environment variable `ODOO_BASE_VERSION` on each migration script, but this is not very handy.
Hopefully this is an acceptable solution :slightly_smiling_face:

2024-06-11 06:50 UTC, aj-fuentes commented on src/util/inherit.py
> +            _logger.info(
We could make almost a warn in CI.
```suggestion
            _logger.log(
                util.NEARLYWARN if util.on_CI() else logging.WARNING,
```

2024-06-11 06:52 UTC, aj-fuentes commented
For info: this also blocks SH custom code upgrade -- it was reported already in some cases. I'd say we should keep it in NEARLYWARN always the noise in SH upgrade tool. @KangOl

2024-07-22 15:02 UTC, KangOl requested changes

2024-07-22 15:02 UTC, KangOl commented on src/util/inherit.py
> +from odoo.upgrade import util
```suggestion
from .const import ENVIRON, NEARLYWARN
from .misc import _cached, parse_version, version_gte
```

2024-07-22 15:02 UTC, KangOl commented on src/util/inherit.py
> +                util.NEARLYWARN if util.on_CI() else logging.WARNING,
```suggestion
               NEARLYWARN,
```

2024-07-23 06:11 UTC, clbr-odoo commented
@KangOl Made the changes, thank you for the review !

2024-07-23 08:29 UTC, KangOl commented
upgradeci retry with always only hr

2024-07-23 13:17 UTC, KangOl approved these changes
@robodoo r+

![](https://cdn2.thecatapi.com/images/584.gif)

2024-07-23 15:06 UTC, closed without merging