[FIX]: allow migrating tables without primary index
odoo/upgrade-util pull request #96
Opened 2024-06-13 07:52 UTC by yajo

During a migration from v12 to v13, this fixes this error:

```
2024-06-12 12:28:54,522 825 CRITICAL db_1732812 odoo.service.server: Failed to initialize database `db_1732812`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/service/server.py", line 1194, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/13.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/13.0/odoo/modules/loading.py", line 424, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/13.0/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/13.0/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/13.0/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmprdd50vnu/migrations/mass_mailing/saas~12.5.2.0/pre-10-models.py", line 21, in migrate
    util.rename_model(cr, "mail.mass_mailing.list_contact_rel", "mailing.contact.subscription")
  File "/tmp/tmprdd50vnu/migrations/util/models.py", line 236, in rename_model
    table_of_model(cr, new),
  File "/tmp/tmprdd50vnu/migrations/util/pg.py", line 1051, in rename_table
    (old_pkey,) = cr.fetchone()
TypeError: 'NoneType' object is not iterable
```

@moduon MT-6161

2024-06-13 07:53 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/upgrade-util/pull/96.png)](https://mergebot.odoo.com/odoo/upgrade-util/pull/96)

2024-06-13 08:15 UTC, aj-fuentes requested changes
Thanks for the patch. Some suggestions below.

2024-06-13 08:15 UTC, aj-fuentes commented on src/util/pg.py
> +    else:
```suggestion
    if cr.rowcount:
```

2024-06-13 08:15 UTC, aj-fuentes commented on src/util/pg.py
> +        )
The indexes can still be renamed, even if no PKey.
```suggestion
    else:
        new_pkey = ""  # no PK renamed
    # rename indexes (except the pkey's one and those not containing $old_table)
    cr.execute(
        """
        SELECT indexname
        FROM pg_indexes
        WHERE tablename = %s
        AND indexname != %s
        AND indexname LIKE %s
        """,
        [new_table, new_pkey, "%" + old_table.replace("_", r"\_") + r"\_%"],
    )
```

2024-06-24 07:54 UTC, yajo commented on src/util/pg.py
> +        AND indexname LIKE %s
this diff is probably meaningless now

2024-06-24 09:40 UTC, aj-fuentes approved these changes
LGTM

2024-06-24 09:58 UTC, KangOl commented
Thank you.

upgradeci skip

@robodoo r+

2024-06-24 16:21 UTC, closed without merging